version: "3.7"
services:
  db:
    image: postgres:14.8
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - api_pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7.2.4
    command: redis-server --appendonly yes
    ports:
      - target: 6379
        published: ${REDIS_PORT}
        protocol: tcp
        mode: host
    volumes:
      - api_redis_data:/data
    restart: always
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  api_redis_data:
  api_pg_data: